# Generated by Django 4.1.10 on 2023-08-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan_app", "0002_account_transaction_loan_operations"),
    ]
    
    operations = [
        migrations.AlterField(
            model_name="customer",
            name="aadhar_id",
            field=models.UUIDField(),
        ),
    ]
