# Generated by Django 4.1.10 on 2023-08-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan_app", "0002_accounttransaction_remove_loan_emi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="aadhar_id",
            field=models.UUIDField(),
        ),
    ]
