# Generated by Django 4.1.10 on 2023-08-03 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loan_app", "0003_alter_customer_aadhar_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="customer",
        ),
    ]
