# Generated by Django 4.1.10 on 2023-08-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan_app", "0006_customer_loan_details"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loandetail",
            old_name="loan_id",
            new_name="loan",
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("car", "car"),
                    ("home", "home"),
                    ("education", "education"),
                    ("personal", "personal"),
                ],
                max_length=25,
            ),
        ),
    ]
